FROM node:22

WORKDIR /app

# Copiar package.json e lock
COPY package*.json ./

# Instalar todas as dependências (incluindo dev)
RUN npm install

# Copiar todo o código
COPY . .

# Expor a porta
EXPOSE 3000

# Rodar com hot reload
CMD ["npm", "run", "dev"]